### ISSUE TITLE
Improve chase solution building using code stratification in aggregation.Chase

### ISSUE THREAD

**Issue by jonasrenault** [NeuroLang/NeuroLang#609]
Can we improve chase solution building in `aggregation.Chase` to better manage stratum resolution?

Some questions and proposed changes:
- deterministic frontend and probabilistic frontend both use `aggregation.chase`; should we implement stratification only in `aggregation.Chase` ?
- Is there a definite order of preference for chase algorithms, such that we should always try to solve strata using `NonRecursiveChase` first, then using `SemiNaive`, then using `Naive` ? Or should this order be configurable ? If so, should we implement a Neurolang.configuration which we've been needing when implementing different RAS backends as well.
- Currently `NonRecursiveChase`, `SemiNaive` and `Naive` all work as superclasses for `aggregation.Chase`, using references to class methods and attributes during chase execution, notably `self.chase_step` and `super().check_constraints`. Can we change them to be standalone classes, that are passed a Chase class as parameter to `execute_chase` and `check_constraints`, such that `aggregation.Chase` can manage the different algorithms for each stratum and call `chase_step` on it selectively ?

Proposed changes are :

 * in `aggregation.Chase` call `check_constraints` at the beginning of `build_chase_solution` to check if program is stratifiable. Maybe rename method to avoid confusion with the other `check_constraints` methods in other Chase classes which will still be called for each stratum.
 * update `aggregation.Chase.check_constraints` to raise an exception if code is not stratifiable ? At the moment this is checked but not used.
 * in `aggregation.Chase.build_chase_solution`, for each stratum, call `check_constraints` in order of preference on `NonRecursiveChase`, `SemiNaive` or `Naive` until one doesn't raise an exception, then call `execute_chase` for this stratum on the selected algorithm.

Also, a bug to fix:

- in `NonRecursiveChase.execute_chase` (which is called by `aggregation.Chase` for each stratum when using this resolution algorithm) for each of the rules in the stratum, we check that symbols in the dependency matrix are solved in order by looking at rules previously seen and putting back the current rule at the end of the pile if it is dependent on an unseen symbol. But this creates an infinite loop if the dependent symbol was seen in a previous stratum. We need to pass the set of rules seen in previous strata to `execute_chase`, at least for `NonRecursiveChase`.

**Comment by demianw** [comment]
1. I think that a meta-chase strategy which stratifies and then chooses the appropriate chase strategy based on each stratum is the winning strategy. Normaly each chase has a `check_constraints` method that verifies if it's applicable to the code. So what you are proposing in your 1.3 point.
2. The preference is NR, SemiNaive, and Naive. But order should be configurable as we have the same pattern with probabilistic cases

Proposed changes
I think that that should be a meta-strategy instead of changing aggregation

The bug fix
Normally the previous strata should be solved and the required symbols are in the Instance that's passed downstream to the case. So for each strata the solution of the previous strata is in the instance and not in the rules.
